#!/usr/bin/env python3
"""Normalize persistent packet-history restore ordering.

The base pass installs the 100-slot LittleFS ring. This wrapper guarantees the
boot replay happens only after LittleFS is mounted and configuration loading has
completed. It also migrates source generated by the earlier pass where the
restore hook appeared before LITTLEFS.begin().
"""

from rev21_persistent_packet_history import main as base_main, MAIN, SETUP_MARKER


def main() -> None:
    base_main()
    text = MAIN.read_text(encoding="utf-8")

    # Remove every old placement, then install exactly once immediately before
    # the Rev2.1 hardware profile is applied. At this point LITTLEFS.begin() and
    # configuration load/default handling have already completed.
    text = text.replace(SETUP_MARKER, "")
    anchor = "  applyTwrRev21HardwareProfile();\n"
    if text.count(anchor) != 1:
        raise SystemExit(f"ERROR: packet history post-mount anchor count={text.count(anchor)}")
    text = text.replace(anchor, SETUP_MARKER + anchor, 1)

    mount_pos = text.find("if (!LITTLEFS.begin(FORMAT_LITTLEFS_IF_FAILED))")
    restore_pos = text.find(SETUP_MARKER.strip())
    config_pos = text.find('if (!LITTLEFS.exists("/default.cfg"))')
    apply_pos = text.find("applyTwrRev21HardwareProfile();")
    if not (0 <= mount_pos < config_pos < restore_pos < apply_pos):
        raise SystemExit(
            "ERROR: persistent history restore must run after LittleFS/config and before hardware profile"
        )

    MAIN.write_text(text, encoding="utf-8")
    print("PASS persistent RF history restore runs after LittleFS mount/config load")


if __name__ == "__main__":
    main()
